version: '3.9'

services:

  nginx:
    build: ./requirements/nginx
    image: ft_nginx
    container_name: frontend
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf:/etc/nginx/sites-available
      - /home/rjada/data/wp:/var/www
    networks:
      - api
    depends_on:
      - wordpress
    
  mariadb:
    build: ./requirements/mariadb
    image: ft_mariadb
    container_name: db
    networks:
      - api
    env_file:
      - .env
    volumes:
      - /home/rjada/data/db:/var/lib/mysql
  
  wordpress:
    build: ./requirements/wordpress
    image: ft_wordpress
    container_name: backend
    volumes:
      - /home/rjada/data/wp:/var/www
    networks:
      - api
    env_file:
      - .env
    depends_on:
      - mariadb

networks:
  api:
    name: lan
    driver: bridge