version: '3.9'

services:

  nginx:
    build: ./requirements/nginx
    image: ft_nginx
    container_name: frontend
    depends_on:
      - wordpress
    restart: always
    volumes:
      - wp-data:/var/www
    networks:
      - api
    ports:
      - "443:443"
    
  mariadb:
    build: ./requirements/mariadb
    image: ft_mariadb
    container_name: db
    restart: always
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - api
  
  wordpress:
    build: ./requirements/wordpress
    image: ft_wordpress
    container_name: backend
    depends_on:
      - mariadb
    restart: always
    volumes:
      - wp-data:/var/www
    env_file:
      - .env
    networks:
      - api

networks:

  api:
    name: lan
    driver: bridge

volumes:

  wp-data:
    name: wp-data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/$USER/data/wp
      
  db-data:
    name: db-data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/$USER/data/db